version: '3.8'
services:
  kttv_webadmin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kttv-web-admin
    environment:
      spring.profiles.active: dev
    ports:
      - "8081:8081"
    tty: true
